openapi: 3.0.0
info:
  title: Multi-Apps Overview Account Invitations SMS Templates API
  description: Frontegg’s Multi-Apps feature simplifies and streamlines application management, delivering a seamless user experience. This section includes all necessary endpoints for managing applications and copying application settings across environments. All endpoints are categorized as **Management Endpoints**, requiring environment-level authorization and providing full control over entitlement resources.
  version: '1.0'
  x-metadata:
    note: Trigger publish artifacts job, remove this x-metadata after publishing
servers:
- url: https://api.frontegg.com/applications
  description: EU Region
- url: https://api.us.frontegg.com/applications
  description: US Region
- url: https://api.ca.frontegg.com/applications
  description: CA Region
- url: https://api.au.frontegg.com/applications
  description: AU Region
- url: https://{domain}.frontegg.com/applications
  description: Frontegg sub-domain for use with user tokens
  variables:
    domain:
      default: app-xxx
tags:
- name: SMS Templates
  x-displayName: SMS templates
paths:
  /resources/configurations/v1/sms/templates:
    servers:
    - url: https://api.frontegg.com/identity
      description: EU Region
    - url: https://api.us.frontegg.com/identity
      description: US Region
    - url: https://api.ca.frontegg.com/identity
      description: CA Region
    - url: https://api.au.frontegg.com/identity
      description: AU Region
    - url: https://{domain}.frontegg.com/identity
      description: Frontegg sub-domain for use with user tokens
      variables:
        domain:
          default: app-xxx
    get:
      operationId: VendorSmsController_getAllSmsTemplates
      summary: Gets Vendor SMS Templates
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplateResponse'
      tags:
      - SMS Templates
      description: Retrieve the SMS templates configured for your environment.
      security:
      - bearer: []
  /resources/configurations/v1/sms/templates/{type}:
    servers:
    - url: https://api.frontegg.com/identity
      description: EU Region
    - url: https://api.us.frontegg.com/identity
      description: US Region
    - url: https://api.ca.frontegg.com/identity
      description: CA Region
    - url: https://api.au.frontegg.com/identity
      description: AU Region
    - url: https://{domain}.frontegg.com/identity
      description: Frontegg sub-domain for use with user tokens
      variables:
        domain:
          default: app-xxx
    get:
      operationId: VendorSmsController_getSmsTemplate
      summary: Gets Vendor SMS Template by Type
      parameters:
      - name: type
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplateResponse'
      tags:
      - SMS Templates
      description: 'Retrieve an SMS template by type.


        Provide the `type` as a path parameter to specify which SMS template to retrieve.'
      security:
      - bearer: []
    delete:
      operationId: VendorSmsController_deleteSmsTemplate
      summary: Deletes Vendor SMS Template by Type
      parameters:
      - name: type
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - SMS Templates
      description: 'Delete an SMS template by type.


        Provide the `type` as a path parameter to specify which SMS template to delete.'
      security:
      - bearer: []
    post:
      operationId: VendorSmsController_createSmsTemplate
      summary: Create or Update a Vendor SMS Template
      parameters:
      - name: type
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSmsTemplateRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplateResponse'
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplateResponse'
      tags:
      - SMS Templates
      description: 'Create or update an SMS template by type.


        Provide the `type` as a path parameter and include the SMS template details in the request body.'
      security:
      - bearer: []
  /resources/configurations/v1/sms/templates/{type}/default:
    servers:
    - url: https://api.frontegg.com/identity
      description: EU Region
    - url: https://api.us.frontegg.com/identity
      description: US Region
    - url: https://api.ca.frontegg.com/identity
      description: CA Region
    - url: https://api.au.frontegg.com/identity
      description: AU Region
    - url: https://{domain}.frontegg.com/identity
      description: Frontegg sub-domain for use with user tokens
      variables:
        domain:
          default: app-xxx
    get:
      operationId: VendorSmsController_getSmsDefaultTemplate
      summary: Gets Vendor Default SMS Template by Type
      parameters:
      - name: type
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplateResponse'
      tags:
      - SMS Templates
      description: 'Retrieve the default SMS template by type.


        Provide the `type` as a path parameter to specify which default SMS template to retrieve.'
      security:
      - bearer: []
  /resources/configurations/v1/sms/templates/default/all:
    servers:
    - url: https://api.frontegg.com/identity
      description: EU Region
    - url: https://api.us.frontegg.com/identity
      description: US Region
    - url: https://api.ca.frontegg.com/identity
      description: CA Region
    - url: https://api.au.frontegg.com/identity
      description: AU Region
    - url: https://{domain}.frontegg.com/identity
      description: Frontegg sub-domain for use with user tokens
      variables:
        domain:
          default: app-xxx
    get:
      operationId: VendorSmsController_getAllSmsDefaultTemplates
      summary: Gets All Vendor Default SMS Templates
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplateResponse'
      tags:
      - SMS Templates
      security:
      - bearer: []
components:
  schemas:
    CreateSmsTemplateRequest:
      type: object
      properties: {}
    SmsTemplateResponse:
      type: object
      properties: {}
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
x-tagGroups:
- name: Management
  tags:
  - Applications settings
